theme: minima
title: Mohibullah Foysal
author: Mohibullah Foysal
description: I am a student at the Green University of Bangladesh. I am passionate about solving problems in new creative ways to drive innovation. By leveraging my development engineering learning I continually look for new and better ways to make tech accessible by all.
